language: node_js
node_js:
- lts/*
addons:
  ssh_known_hosts: 35.233.171.1
script:
- npm run atomize
- npm run build
- ls -l build
- openssl aes-256-cbc -K $encrypted_341df442da41_key -iv $encrypted_341df442da41_iv
  -in deploy-rsa.enc -out /tmp/deploy-rsa -d
- chmod 600 /tmp/deploy-rsa
- eval `ssh-agent`
- ssh-add /tmp/deploy-rsa
- rsync -avzcP build/ kailangfu@35.233.171.1:/home/kailangfu/www/thmix.org/
- kill $SSH_AGENT_PID